// XAU Adaptive Regime Engine V10.2
// Exit experiment: pure runner, delayed BE, wide ATR trail.
// Based on V10.01 entry/regime engine; entry logic intentionally unchanged.
#property strict
#property version "10.20"
#property description "XAU Adaptive Regime V10.2 - pure runner exit experiment"
#include <Trade/Trade.mqh>
CTrade trade;

enum StrategyMode { MODE_ADAPTIVE=0, MODE_TREND_ONLY=1, MODE_REVERSAL_ONLY=2 };
enum SessionMode { SESSION_LONDON_NY=0, SESSION_LONDON_ONLY=1, SESSION_NEWYORK_ONLY=2 };
input double RiskPercent=0.50, MaxRiskPercent=0.75, MaxDailyLossPercent=1.50, DailyProfitTargetUSD=100.0;
input int MaxTradesPerDay=4, MaxConsecutiveLosses=3, CooldownMinutes=30;
input double MaxLotSize=0.50; input bool RejectMinLotIfRiskExceeded=true;
input SessionMode TradingSession=SESSION_LONDON_NY; input bool UseSessionFilter=true;
input int LondonStartHour=8,LondonEndHour=12,NewYorkStartHour=13,NewYorkEndHour=20;
input StrategyMode Mode=MODE_ADAPTIVE; input ENUM_TIMEFRAMES RegimeTF=PERIOD_H4,BiasTF=PERIOD_H1,EntryTF=PERIOD_M15;
input int FastMAPeriod=50,SlowMAPeriod=200,ADXPeriod=14,StructureLookback=12;
input double MinADXTrend=18.0,StrongADX=25.0;
input int ATRPeriod=14,ATRBaselineBars=48; input double MinATRPrice=0.40,MinATRRatio=0.80,ExpansionATRRatio=1.25,ExtremeATRRatio=2.20,MaxSpreadATRPercent=12.0;
input double BreakoutBufferATR=0.10,RetestToleranceATR=0.30,MinBodyATR=0.20,MinCloseLocation=0.60; input bool RequireVWAPAlignment=true;
input double SweepATR=0.10,ReentryATR=0.05,MaxSweepATR=0.80; input bool RequireReversalCandle=true;
// V10.2 EXIT ENGINE: no partial TP, delayed BE, wide runner trail
input double StopATRBuffer=0.25,MinStopATR=0.90,MaxStopATR=2.50;
input double PartialTP_R=999.0,PartialClosePercent=0.0;
input double RunnerStart_R=2.00,TrailATR=3.20,StrongTrailATR=4.00;
input double BreakEven_R=1.50,BreakEvenLock_R=0.05;
input int MaxTradeMinutes=480,MagicNumber=91020,DeviationPoints=40; input string TradeComment="XAU ADAPTIVE V10.2";
string Sym; int H4Fast=-1,H4Slow=-1,H4ADX=-1,H1Fast=-1,H1Slow=-1,H1ADX=-1,ATRHandle=-1; datetime DayStart=0,LastEntry=0,LastExit=0,LastBar=0; double DayStartEquity=0; int TradesToday=0,LossStreak=0; ulong StateTicket=0; double StateEntry=0,StateRisk=0,StatePeak=0;
bool Buf(int h,int b,int s,double &v){if(h<0)return false;double x[];ArraySetAsSeries(x,true);if(CopyBuffer(h,b,s,1,x)!=1)return false;v=x[0];return true;}
double ATR(int s=1){double v=0;return Buf(ATRHandle,0,s,v)?v:0;}
double AvgATR(){double s=0;int n=0;for(int i=2;i<2+ATRBaselineBars;i++){double v=ATR(i);if(v>0){s+=v;n++;}}return n?s/n:0;}
double ATRRatio(double a){double b=AvgATR();return(a>0&&b>0)?a/b:0;}
bool NewBar(){datetime t=iTime(Sym,EntryTF,0);if(t<=0||t==LastBar)return false;LastBar=t;return true;}
void ResetDay(){MqlDateTime d;TimeToStruct(TimeCurrent(),d);d.hour=0;d.min=0;d.sec=0;datetime x=StructToTime(d);if(x!=DayStart){DayStart=x;DayStartEquity=AccountInfoDouble(ACCOUNT_EQUITY);TradesToday=0;LossStreak=0;}}
bool InSession(){if(!UseSessionFilter)return true;MqlDateTime d;TimeToStruct(TimeCurrent(),d);int h=d.hour;bool l=h>=LondonStartHour&&h<LondonEndHour,n=h>=NewYorkStartHour&&h<NewYorkEndHour;if(TradingSession==SESSION_LONDON_ONLY)return l;if(TradingSession==SESSION_NEWYORK_ONLY)return n;return l||n;}
bool DailyBlocked(){double e=AccountInfoDouble(ACCOUNT_EQUITY),p=e-DayStartEquity;if(DayStartEquity<=0)return true;if(DailyProfitTargetUSD>0&&p>=DailyProfitTargetUSD)return true;if(p<=-(DayStartEquity*MaxDailyLossPercent/100.0))return true;if(TradesToday>=MaxTradesPerDay||LossStreak>=MaxConsecutiveLosses)return true;return false;}
bool SpreadOK(double a){double ask=SymbolInfoDouble(Sym,SYMBOL_ASK),bid=SymbolInfoDouble(Sym,SYMBOL_BID);return ask>0&&bid>0&&a>0&&(ask-bid)<=a*MaxSpreadATRPercent/100.0;}
int DirTF(int fh,int sh,int ah,ENUM_TIMEFRAMES tf){double f,s,a,p,m;if(!Buf(fh,0,1,f)||!Buf(sh,0,1,s)||!Buf(ah,0,1,a)||!Buf(ah,1,1,p)||!Buf(ah,2,1,m))return 0;double c=iClose(Sym,tf,1);if(c<=0||a<MinADXTrend)return 0;if(c>f&&f>s&&p>m)return 1;if(c<f&&f<s&&m>p)return -1;return 0;}
int Regime(){int a=DirTF(H4Fast,H4Slow,H4ADX,RegimeTF),b=DirTF(H1Fast,H1Slow,H1ADX,BiasTF);return(a!=0&&a==b)?a:0;}
bool Strong(){double a=0;return Buf(H1ADX,0,1,a)&&a>=StrongADX;}
double Hi(int n,int st=1){double x=-DBL_MAX;for(int i=st;i<st+n;i++)x=MathMax(x,iHigh(Sym,EntryTF,i));return x;}
double Lo(int n,int st=1){double x=DBL_MAX;for(int i=st;i<st+n;i++)x=MathMin(x,iLow(Sym,EntryTF,i));return x;}
double VWAP(int n=32){double p=0,vv=0;for(int i=1;i<=n;i++){double h=iHigh(Sym,EntryTF,i),l=iLow(Sym,EntryTF,i),c=iClose(Sym,EntryTF,i);long v=iVolume(Sym,EntryTF,i);if(h<=0||l<=0||c<=0)continue;double w=v>0?(double)v:1;p+=(h+l+c)/3.0*w;vv+=w;}return vv?p/vv:0;}
bool Bull(){return Hi(StructureLookback,1)>Hi(StructureLookback,StructureLookback+1)&&Lo(StructureLookback,1)>Lo(StructureLookback,StructureLookback+1);}
bool Bear(){return Hi(StructureLookback,1)<Hi(StructureLookback,StructureLookback+1)&&Lo(StructureLookback,1)<Lo(StructureLookback,StructureLookback+1);}
bool Pullback(int d,double a){double level=d>0?Hi(StructureLookback,2):Lo(StructureLookback,2);double c=iClose(Sym,EntryTF,1),o=iOpen(Sym,EntryTF,1),h=iHigh(Sym,EntryTF,1),l=iLow(Sym,EntryTF,1),c2=iClose(Sym,EntryTF,2);if(c<=0||MathAbs(c-o)<a*MinBodyATR)return false;double v=VWAP();if(RequireVWAPAlignment&&v>0&&((d>0&&c<v)||(d<0&&c>v)))return false;if(d>0&&!Bull())return false;if(d<0&&!Bear())return false;bool ret=d>0?(l<=level+a*RetestToleranceATR&&c>level&&c2>level):(h>=level-a*RetestToleranceATR&&c<level&&c2<level);if(!ret||((d>0)?c<=o:c>=o))return false;double loc=h-l>0?(d>0?(c-l)/(h-l):(h-c)/(h-l)):0;return loc>=MinCloseLocation;}
bool Sweep(int d,double a){double hi=Hi(StructureLookback,2),lo=Lo(StructureLookback,2),c=iClose(Sym,EntryTF,1),o=iOpen(Sym,EntryTF,1),h=iHigh(Sym,EntryTF,1),l=iLow(Sym,EntryTF,1);if(d<0)return h>hi+a*SweepATR&&h<hi+a*MaxSweepATR&&c<hi-a*ReentryATR&&(!RequireReversalCandle||c<o);return l<lo-a*SweepATR&&l>lo-a*MaxSweepATR&&c>lo+a*ReentryATR&&(!RequireReversalCandle||c>o);}
int Signal(double a){double r=ATRRatio(a);if(a<MinATRPrice||r<MinATRRatio||r>=ExtremeATRRatio)return 0;int d=Regime();if(Mode!=MODE_REVERSAL_ONLY&&d!=0){if(Pullback(d,a))return d;if(r>=ExpansionATRRatio){double c=iClose(Sym,EntryTF,1);if(d>0&&c>Hi(StructureLookback,2)+a*BreakoutBufferATR)return 1;if(d<0&&c<Lo(StructureLookback,2)-a*BreakoutBufferATR)return -1;}}if(Mode!=MODE_TREND_ONLY){if(Sweep(-1,a))return -1;if(Sweep(1,a))return 1;}return 0;}
bool HasPos(ulong &t){t=0;for(int i=PositionsTotal()-1;i>=0;i--){ulong x=PositionGetTicket(i);if(x&&PositionSelectByTicket(x)&&PositionGetString(POSITION_SYMBOL)==Sym&&PositionGetInteger(POSITION_MAGIC)==MagicNumber){t=x;return true;}}return false;}
void State(){ulong t;if(!HasPos(t)){StateTicket=0;StateRisk=0;StateEntry=0;StatePeak=0;return;}if(!PositionSelectByTicket(t))return;if(t!=StateTicket){StateTicket=t;StateEntry=PositionGetDouble(POSITION_PRICE_OPEN);StateRisk=MathAbs(StateEntry-PositionGetDouble(POSITION_SL));StatePeak=StateEntry;}}
double Loss(ENUM_ORDER_TYPE ty,double vol,double dist){double e=ty==ORDER_TYPE_BUY?SymbolInfoDouble(Sym,SYMBOL_ASK):SymbolInfoDouble(Sym,SYMBOL_BID),s=ty==ORDER_TYPE_BUY?e-dist:e+dist,p=0;if(!OrderCalcProfit(ty,Sym,vol,e,s,p))return 0;return MathAbs(p);}
double Lots(ENUM_ORDER_TYPE ty,double dist){double money=AccountInfoDouble(ACCOUNT_EQUITY)*MathMin(RiskPercent,MaxRiskPercent)/100.0,min=SymbolInfoDouble(Sym,SYMBOL_VOLUME_MIN);if(money<=0)return 0;if(RejectMinLotIfRiskExceeded&&Loss(ty,min,dist)>money*1.02)return 0;double ts=SymbolInfoDouble(Sym,SYMBOL_TRADE_TICK_SIZE),tv=SymbolInfoDouble(Sym,SYMBOL_TRADE_TICK_VALUE),step=SymbolInfoDouble(Sym,SYMBOL_VOLUME_STEP);if(ts<=0||tv<=0)return 0;double lot=money/((dist/ts)*tv),maxv=MathMin(MaxLotSize,SymbolInfoDouble(Sym,SYMBOL_VOLUME_MAX));lot=MathMin(lot,maxv);if(step>0)lot=MathFloor(lot/step)*step;if(lot<min)return 0;return NormalizeDouble(lot,2);}
bool Open(int d,double a){ulong t;if(HasPos(t)||DailyBlocked()||!InSession())return false;if(TimeCurrent()-LastEntry<CooldownMinutes*60||TimeCurrent()-LastExit<CooldownMinutes*60)return false;double entry=d>0?SymbolInfoDouble(Sym,SYMBOL_ASK):SymbolInfoDouble(Sym,SYMBOL_BID),swing=d>0?Lo(StructureLookback,1):Hi(StructureLookback,1),raw=d>0?entry-(swing-a*StopATRBuffer):(swing+a*StopATRBuffer)-entry,dist=MathMax(raw,a*MinStopATR);dist=MathMin(dist,a*MaxStopATR);ENUM_ORDER_TYPE ty=d>0?ORDER_TYPE_BUY:ORDER_TYPE_SELL;double lot=Lots(ty,dist);if(lot<=0)return false;int dig=(int)SymbolInfoInteger(Sym,SYMBOL_DIGITS);double sl=d>0?entry-dist:entry+dist;trade.SetExpertMagicNumber(MagicNumber);trade.SetDeviationInPoints(DeviationPoints);bool ok=d>0?trade.Buy(lot,Sym,entry,NormalizeDouble(sl,dig),0,TradeComment):trade.Sell(lot,Sym,entry,NormalizeDouble(sl,dig),0,TradeComment);if(ok){LastEntry=TimeCurrent();TradesToday++;State();}return ok;}
void Manage(){ulong t;if(!HasPos(t)||!PositionSelectByTicket(t))return;State();ENUM_POSITION_TYPE ty=(ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);double open=PositionGetDouble(POSITION_PRICE_OPEN),sl=PositionGetDouble(POSITION_SL),price=ty==POSITION_TYPE_BUY?SymbolInfoDouble(Sym,SYMBOL_BID):SymbolInfoDouble(Sym,SYMBOL_ASK),risk=StateRisk;if(risk<=0)return;if(ty==POSITION_TYPE_BUY)StatePeak=MathMax(StatePeak,price);else StatePeak=StatePeak==0?price:MathMin(StatePeak,price);double r=ty==POSITION_TYPE_BUY?(price-open)/risk:(open-price)/risk;if((int)((TimeCurrent()-(datetime)PositionGetInteger(POSITION_TIME))/60)>=MaxTradeMinutes){if(trade.PositionClose(t))LastExit=TimeCurrent();return;}int dig=(int)SymbolInfoInteger(Sym,SYMBOL_DIGITS);double a=ATR(1),ns=sl;if(r>=BreakEven_R){double lock=ty==POSITION_TYPE_BUY?open+risk*BreakEvenLock_R:open-risk*BreakEvenLock_R;if(ty==POSITION_TYPE_BUY)ns=MathMax(ns,lock);else ns=ns==0?lock:MathMin(ns,lock);}if(r>=RunnerStart_R&&a>0){double mult=Strong()?StrongTrailATR:TrailATR,tr=ty==POSITION_TYPE_BUY?StatePeak-mult*a:StatePeak+mult*a;if(ty==POSITION_TYPE_BUY)ns=MathMax(ns,tr);else ns=ns==0?tr:MathMin(ns,tr);}double pt=SymbolInfoDouble(Sym,SYMBOL_POINT);if(ty==POSITION_TYPE_BUY&&ns>sl+pt)trade.PositionModify(t,NormalizeDouble(ns,dig),0);if(ty==POSITION_TYPE_SELL&&ns>0&&(sl==0||ns<sl-pt))trade.PositionModify(t,NormalizeDouble(ns,dig),0);}
void Stats(){static datetime scan=0;datetime from=scan?scan:DayStart;if(!HistorySelect(from,TimeCurrent()))return;int n=HistoryDealsTotal();for(int i=n-1;i>=0;i--){ulong d=HistoryDealGetTicket(i);if(!d)continue;if(HistoryDealGetInteger(d,DEAL_MAGIC)!=MagicNumber||HistoryDealGetString(d,DEAL_SYMBOL)!=Sym)continue;datetime tm=(datetime)HistoryDealGetInteger(d,DEAL_TIME);if(tm<=scan)break;if(HistoryDealGetInteger(d,DEAL_ENTRY)==DEAL_ENTRY_OUT||HistoryDealGetInteger(d,DEAL_ENTRY)==DEAL_ENTRY_OUT_BY){double p=HistoryDealGetDouble(d,DEAL_PROFIT)+HistoryDealGetDouble(d,DEAL_SWAP)+HistoryDealGetDouble(d,DEAL_COMMISSION);if(p<0)LossStreak++;else if(p>0)LossStreak=0;LastExit=tm;}if(tm>scan)scan=tm;}}
int OnInit(){Sym=_Symbol;trade.SetExpertMagicNumber(MagicNumber);H4Fast=iMA(Sym,RegimeTF,FastMAPeriod,0,MODE_EMA,PRICE_CLOSE);H4Slow=iMA(Sym,RegimeTF,SlowMAPeriod,0,MODE_EMA,PRICE_CLOSE);H4ADX=iADX(Sym,RegimeTF,ADXPeriod);H1Fast=iMA(Sym,BiasTF,FastMAPeriod,0,MODE_EMA,PRICE_CLOSE);H1Slow=iMA(Sym,BiasTF,SlowMAPeriod,0,MODE_EMA,PRICE_CLOSE);H1ADX=iADX(Sym,BiasTF,ADXPeriod);ATRHandle=iATR(Sym,EntryTF,ATRPeriod);if(H4Fast<0||H4Slow<0||H4ADX<0||H1Fast<0||H1Slow<0||H1ADX<0||ATRHandle<0)return INIT_FAILED;ResetDay();return INIT_SUCCEEDED;}
void OnDeinit(const int r){if(H4Fast>=0)IndicatorRelease(H4Fast);if(H4Slow>=0)IndicatorRelease(H4Slow);if(H4ADX>=0)IndicatorRelease(H4ADX);if(H1Fast>=0)IndicatorRelease(H1Fast);if(H1Slow>=0)IndicatorRelease(H1Slow);if(H1ADX>=0)IndicatorRelease(H1ADX);if(ATRHandle>=0)IndicatorRelease(ATRHandle);}
void OnTick(){ResetDay();Stats();Manage();ulong t=0;if(HasPos(t))return;if(!NewBar()||DailyBlocked()||!InSession())return;double a=ATR(1);if(a<=0||!SpreadOK(a))return;int s=Signal(a);if(s)Open(s,a);}
